version: '3'
services:
  traefik:
    build: .
    container_name: ${PROJECT_NAME}
    restart: always
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/conf:ro
      - ./scripts:/scripts:ro
      - ./data/:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}-auth.basicauth.usersfile=/data/.htpasswd"
      - "traefik.http.routers.${PROJECT_NAME}.middlewares=https-redirect@file"
      - "traefik.http.routers.${PROJECT_NAME}-sec.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}-sec.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}-sec.middlewares=${PROJECT_NAME}-auth"
      - "traefik.http.routers.${PROJECT_NAME}-sec.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-sec.tls.options=myTLSOptions@file"
      - "traefik.http.routers.${PROJECT_NAME}-sec.tls.certresolver=le"
      - "traefik.http.routers.${PROJECT_NAME}-sec.service=api@internal"
    environment:
      HTACCESS_USER: ${HTACCESS_USER}
      HTACCESS_PASS: ${HTACCESS_PASS}
      ACME_EMAIL: ${ACME_EMAIL}
      TRAEFIK_ERROR_LOG_LEVEL: ${TRAEFIK_ERROR_LOG_LEVEL}
      TRAEFIK_ERROR_LOG_FILE_PATH: ${TRAEFIK_ERROR_LOG_FILE_PATH}
      TRAEFIK_GLOBAL_CHECK_NEW_VERSION: ${TRAEFIK_GLOBAL_CHECK_NEW_VERSION}
      TRAEFIK_GLOBAL_SEND_ANONYMOUS_USAGE: ${TRAEFIK_GLOBAL_SEND_ANONYMOUS_USAGE}
      TRAEFIK_API_DASHBOARD: ${TRAEFIK_API_DASHBOARD}
      TRAEFIK_API_DEBUG: ${TRAEFIK_API_DEBUG}
      MIDDLEWARE_HEADERS_CUSTOM_FRAME_OPTIONS_VALUE: ${MIDDLEWARE_HEADERS_CUSTOM_FRAME_OPTIONS_VALUE}
      MIDDLEWARE_HEADERS_SSL_REDIRECT: ${MIDDLEWARE_HEADERS_SSL_REDIRECT}
      MIDDLEWARE_HEADERS_BROWSER_XSS_FILTER: ${MIDDLEWARE_HEADERS_BROWSER_XSS_FILTER}
      MIDDLEWARE_HEADERS_CONTENT_TYPE_NO_SNIFF: ${MIDDLEWARE_HEADERS_CONTENT_TYPE_NO_SNIFF}
      MIDDLEWARE_HEADERS_FORCE_STS_HEADER: ${MIDDLEWARE_HEADERS_FORCE_STS_HEADER}
      MIDDLEWARE_HEADERS_STS_SECONDS: ${MIDDLEWARE_HEADERS_STS_SECONDS}
      MIDDLEWARE_HEADERS_STS_INCLUDE_SUBDOMAINS: ${MIDDLEWARE_HEADERS_STS_INCLUDE_SUBDOMAINS}
      MIDDLEWARE_HEADERS_STS_PRELOAD: ${MIDDLEWARE_HEADERS_STS_PRELOAD}
      MIDDLEWARE_TLS_MIN_VERSION: ${MIDDLEWARE_TLS_MIN_VERSION}
      MIDDLEWARE_HTTPS_REDIRECT_SCHEME: ${MIDDLEWARE_HTTPS_REDIRECT_SCHEME}

networks:
  web:
    external: true